### ISSUE TITLE
Repository title description is too long

### ISSUE THREAD

**Issue by abrie** [Mastermind64222-0/indigenous-namibia#1]
Github style guide recommend that this be just a title and a link.

![issue](https://github-cloud.s3.amazonaws.com/assets/1462268/10564970/e8a3d328-7593-11e5-805a-bd2f0b99217f.png)

**Comment by Mastermind64222-0** [comment]
Alright, changing it now

**Comment by abrie** [comment]
When an issue has been addressed,  press the "close and comment" button on the issue editor.
