### ISSUE TITLE
Provide means to correct misspelled words

### ISSUE THREAD

**Issue by abrie** [Mastermind64222-0/indigenous-namibia#13]
Currently there is no way to edit a translation once it's been placed into the system. A registered user should be able to look up a misspelled word, edit it, and resubmit it to the system.

**Comment by Mastermind64222-0** [comment]
That would be great. It was noticed and raised by one of the testers. One also mentioned that the casting of the worda being translated was sensitive even if it's the same word. Any thoughts that? If we can perhaps make it case insensitive as long as they match "car" and "Car" and if a word already exists

**Comment by abrie** [comment]
I've logged the case sensitivity as a bug, issue #14

**Comment by abrie** [comment]
The current dev branch now implements a "flag" feature available to registered users. Clicking the flag button re-creates the translation request so that its fields may be edited.

The re-created translation request cannot be edited, because of the DB was not designed with corrections in mind. Some re-engineering is required to get this feature to work right.

So, at present, the dev branch shows the gui for this system, along with about 1/3 of the back end implementation. Interested developers should look at the 'flag' method in the translation requests controller.

**Comment by abrie** [comment]
Implemented and deployed in tag v0.5.1
