### ISSUE TITLE
Go Back Home Navigation

### ISSUE THREAD

**Issue by Mastermind64222-0** [Mastermind64222-0/indigenous-namibia#20]
When user is clicks on the "Log in" or "Sign up” and moves to the respective views, there is no link or navigation that allows them to go back to the home page, should they decide not to do the any of the two (sign up or login).

**Comment by abrie** [comment]
NIL home link is now displayed in upper left when on login or sign_up pages

**Comment by Mastermind64222-0** [comment]
Well noted.
