### ISSUE TITLE
Local Languages Metadata

### ISSUE THREAD

**Issue by Mastermind64222-0** [Mastermind64222-0/indigenous-namibia#22]
View for displaying currently existing local languages with an indication of the total number of word entries for each and how translations.

**Comment by abrie** [comment]
Please clarify, what does "and how translations" mean?

**Comment by abrie** [comment]
More metadata has been added in the Dashboard QuickStats section: a4bf42e
Can this issue be considered closed?

**Comment by Mastermind64222-0** [comment]
Yes, it can now be considered closed.
