### ISSUE TITLE
Frequently Requested Word(s)

### ISSUE THREAD

**Issue by Mastermind64222-0** [Mastermind64222-0/indigenous-namibia#23]
Preferred word sort in "Unanswered Translation Requests" table to have the most frequently requested  words to be at the top of the table and have preference over the least requested. This helps the different translators translate or informs them as to which words the users need a translation to the most, even though in the end all requested words will end up being translated.

**Comment by abrie** [comment]
Issue corrected in master, 09b03d96c0f72fe6eaf7aeb986fe66ac38fc02c9
